config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = People.new
  end

  def show
    @person = People.find(params[:name])
  end

  def index
    @person = People.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>People#index</h1>
<p>Find me in app/views/people/index.html.erb</p>
<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Show person', person_path(person) %>
<% end %>

app/views/people/new.html.erb
<h1>People#home</h1>
<p>Find me in app/views/people/home.html.erb</p>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h4><%= @person.age %></h1>
<p><%= @person.hair_color %></p>
<%= link_to 'Back', people_path %>